# Generated by Django 5.2.7 on 2025-11-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_delete_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
